server:
  - "server/**"

client:
  - "client/**"

docs:
  - "**/*.md"

github-actions:
  - ".github/**"

database:
  - "server/**/Migrations/**"
  - "server/**/Data/**"

api:
  - "server/**/Controllers/**"

models:
  - "server/**/Models/**"

services:
  - "server/**/Services/**"

ui:
  - "client/**/components/**"

pages:
  - "client/**/pages/**"
